[package]
name = "Hashing_algo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.10.6"
md5 = "0.7.0"
sha2 = "0.10.8"
whirlpool = "0.10.4"
